### ISSUE TITLE
Integrate PCAP Parser with Datastore

### ISSUE THREAD

**Issue by mnuzen** [mnuzen/step-capstone-2020#10]
Enable loading of data into datastore through packet parser. We want to extract the following attributes from any given PCAP file:
- Source: IP populated by PCAP parser
- Destination: IP populated by PCAP parser
- Protocol: populated by PCAP parser
- Size: populated by PCAP parser
- Frequency: populated by PCAP parser

See design doc for all attributes stored in database.

**Comment by arunk054** [comment]
Do we have a schema of the table or the fields that the packet parser would like to persist into the data store?
