### ISSUE TITLE
Add interfaces for common module usage

### ISSUE THREAD

**Issue by thorncorona** [mnuzen/step-capstone-2020#13]
Add interfaces to make testing/merge possible. 

- [x] GeoIP
- [x] Frequency lookup
- [x] Malicious IP
- [x] DNS lookup

**Comment by thorncorona** [comment]
Interfaces for PCAP/Geo added in #9

**Comment by Erik-Handeland** [comment]
Interfaces for Malicious IP added in #27

**Comment by thorncorona** [comment]
Interface for DNS in #19

**Comment by mnuzen** [comment]
Frequency computations in #23

**Comment by thorncorona** [comment]
Looks to be done. Closing @mnuzen @Erik-Handeland
