### ISSUE TITLE
Create PCAP loader to retrieve data based on specific filenames

### ISSUE THREAD

**Issue by mnuzen** [mnuzen/step-capstone-2020#32]
- Retrieve specific data from datastore 
- Send to visualizations

**Comment by arunk054** [comment]
By specific data, do you mean the data for different use cases like Geo tagging, Bad IPs etc.? According to the original design each of these should be a separate service that reads raw data and processes everytime (optionally caching). So would not recommend storing processed data itself in the primary data store, it can be more like an LRU cache.

**Comment by mnuzen** [comment]
Specific data would be retrieving all data in datastore that's tagged under one filename entity -- I think we'll have to fix this to when we separate the parsing and processing but I just needed something to retrieve data for my network visualization for the MVP for now
