### ISSUE TITLE
Finish MVP website

### ISSUE THREAD

**Issue by thorncorona** [mnuzen/step-capstone-2020#37]
1. Solidify web pages 
2. Link web pages together
3. Get rid of extraneous content on web pages.o

Also added milestones to the project so we can differentiate between stuff that needs to get done by Fri/8-17. Please tag your issues appropriately :)

**Comment by thorncorona** [comment]
Created branch `mvp` containing revised website.

**Comment by thorncorona** [comment]
Melba and I finished updating our pages. @Erik-Handeland I did an initial merge for you as well, can you update yours?

**Comment by Erik-Handeland** [comment]
@thorncorona  Done
