### ISSUE TITLE
Populate & reorder website page sequence

### ISSUE THREAD

**Issue by mnuzen** [mnuzen/step-capstone-2020#67]
- add all pages to website
- structure order of pages to fit with learning process (starting off broad with high level things like country, domain, then diving deeper into details like packet protocol, IP prefix)

Current Order:
1. Welcome Page
2. File Selector Page
3. Map Vis
4. Network Vis
5. Tables Vis
6. Bucket Vis
7. Domains Vis

**Comment by mnuzen** [comment]
Removed additional charts visualization page (charts.html) and added to bucket visualization page:
![Screenshot 2020-08-24 at 11 48 04 AM](https://user-images.githubusercontent.com/43756178/91083812-c56e9000-e5ff-11ea-84c5-2a1b6e1966b5.png)

**Comment by mnuzen** [comment]
Final Order of Pages: 

1.  Welcome Page
2. File Selector Page
3. Map Visualization
4. Domains Visualization
5. Network Visualization
6. Tables Visualization
7. Bucket Visualization

**Comment by mnuzen** [comment]
Need to add source of PCAP files 
- [File 1 source](https://tcpreplay.appneta.com/wiki/captures.html)
[Website](https://tcpreplay.appneta.com/)

**Comment by mnuzen** [comment]
New Order:

1. Welcome Page
2. File Selector
3. Map Visualization
4. Domain Visualization
5. Malicious IP Visualization
6. Network Frequency Visualization
7. Bucket Visualization

**Comment by thorncorona** [comment]
@mnuzen can we close this issue?
